cloud-barista/cb-dragonfly

file/conf/telegraf.conf, pkg/collector/host.go, pkg/collector/metric_collector.go, pkg/manager/apiserver.go, pkg/manager/manager.go, pkg/manager/scheduler.go, pkg/metricstore/influxdbv1/influxdb.go
- CB-Dragonfly 모듈 주석 제거 및 테스트 코드 정리
=> 주석 및 테스트코드 정리

pkg/collector/aggregator.go, pkg/collector/metric_collector.go, pkg/metricstore/influxdbv1/influxdb.go
- seperating hostIdOstype value(tag logic)
=> Modify tagging logic

pkg/manager/apiserver.go
=> [Bug] 모니터링 정보 조회 버그 픽스

pkg/api/grpc/request/mon/mon.go, pkg/api/grpc/request/monapi.go, pkg/api/grpc/request/test/grpc_conf.yaml, pkg/api/grpc/request/test/test_api.go
- grpc 클라이언트 api 추가
- api 샘플코드 추가 ( pkg/api/grpc/request/test/test_api.go )
=> Add grpc client api

pkg/api/rest/healthcheck/healthcheck.go, pkg/manager/apiserver.go
=> 헬스체크 API 추가

README.md
This PR updates outdated contents in README.md
=> Update outdated contents in README.md

.gitignore
=> [프로젝트 파일 정리] 불필요 파일 정리 및 gitignore 항목 추가

pkg/manager/manager.go
- 재시도 횟수 : 5초 (5s)
- 재시도 시간 간격 : 5초 (5s)
=> Kafka 연결 재시도 로직 추가

pkg/core/config/config.go
=> [버그픽스] config 설정 관련 버그 픽스

pkg/core/alert/task/task.go, pkg/manager/manager.go
- 알람 모듈 expression 관련 생성 버그 픽스
=> [알람 모듈] 알람 모듈 expression 관련 생성 버그 픽스

pkg/collector/metric_collector.go, pkg/manager/manager.go, pkg/manager/scheduler.go
[버그 픽스] Kafka TCP 커넥션 프로세스 비정상 동작
- 현상 : Kafka TCP 커넥션 프로세스 무한 생성
- 원인 :
(1) 메트릭 콜렉터 고루틴 종료 로직 미동작(Go 채널 로직 버그로 인한 미동작)
(2) 스케일-인의 비정상 동작(연산 로직 버그로 인한 콜렉터 삭제 로직 수행 X, 좀비 메트릭 콜렉터 고루틴 생성)
- 해결 사항 :
(1) 메트릭 콜렉터 내부 로직 & 스케쥴러 스케일-인 로직 고도화
[버그 픽스] Kafka 토픽 처리 비정상 동작
- 현상 : 좀비 토픽 생성 및 건강한 토픽 처리 X
- 원인 : DF 콜렉터 로직 버그
- 해결 사항 :
(1) 콜렉터의 토픽 Subscribe & Unsubcribe & Delete 로직 고도화 : 동작 시나리오 별 로직 분기 및 순차 & 예외 처리
(2) 정상 동작하는 토픽 체크를 위한 Topic Heartbeat 로직 추가
=> [버그 픽스] Kafka TCP 커넥션 프로세스 비정상 동작

pkg/core/alert/event/event.go, pkg/manager/main/main.go
- 알람 이벤트 로그 목록 조회 시 쿼리 파라미터 적용
=> [알람 모듈] 알람 이벤트 로그 목록 조회 시 쿼리 파라미터 적용

pkg/manager/main/main.go
- push 정책 관련 config 정보 설정 로직 누락으로 인한 버그
- config 정보 설정 로직 추가
=> [버그 픽스] PUSH 모듈 오동작 버그 픽스

file/conf/telegraf.conf, file/install_mcis_script.sh, file/uninstall_mcis_script.sh, pkg/core/agent/agent.go, pkg/core/metric/ondemand_metric.go, pkg/manager/apiserver.go, pkg/metricstore/influxdb/v1/query.go, pkg/puller/aggregator.go
- Agent 설정 파일 불필요 코드 삭제
* InfluxDB Output Plugin 설정 삭제
- Agent 설치 파일 수정
* 쉘 스크립트 파일 내부 명칭 변화
* 패키지 삭제 명령어 오류 수정
- Aggregate 데이터 Tag 조회 로직 수정
- Push/Pull 모니터링 메트릭 저장 Tag 동기화
- 에이전트 설치/삭제 API 정리
=> CB-Dragonfly 카페모카 기능 개선

conf/config.yaml, pkg/config/config.go, pkg/metricstore/influxdb/v1/influxdb.go
=> Retention Policy 설정 기능 추가

docker-compose-dev-df.yaml, docker-compose.yaml
=> Update exposing ports for InfluxDB

Makefile, conf/config.yaml, docker-compose.yaml, pkg/collector/collector.go, pkg/config/config.go, pkg/core/agent/agent.go, pkg/manager/main/main.go, pkg/metricstore/influxdb/v1/influxdb.go
이슈 #101 관련 버그 수정
- docker-compose 환경 InfluxDB 포트 설정 관련 버그 수정
=> [공통] docker-compose 환경 InfluxDB 포트 설정 관련 버그 수정

conf/config.yaml
- config 파일 주석 및 기본 동작 방식 수정 (기본 push 방식, avg 함수 기반 aggregate)
=> [공통] config 파일 주석 및 기본 동작 방식 수정 (기본 push 방식, avg 함수 기반 aggregate)

pkg/collector/aggregator.go, pkg/metricstore/influxdb/v1/query.go
- query 조회 버그 수정 및 메트릭 누락 항목 추가
=> [bugfix] query 조회 버그 수정 및 메트릭 누락 항목 추가

pkg/api/rest/agent/agent.go, pkg/api/rest/agent/metadata.go, pkg/api/rest/alert/eventhandler.go, pkg/api/rest/alert/task.go, pkg/api/rest/common.go, pkg/api/rest/config/config.go, pkg/api/rest/metric/mcis_metric.go, pkg/core/config/config.go, pkg/docs/docs.go, pkg/docs/swagger.json, pkg/docs/swagger.yaml
- POST, PUT 요청에 대해 기존 form 형태에서 Json으로 변경
- Swagger 수정
=>  [공통] API FORM -> JSON 변경

helm/cb-dragonfly/Chart.yaml, pkg/api/rest/agent/agent.go, pkg/modules/procedure/push/collector/k8s_collector/main.go, pkg/types/constant.go, pkg/util/utility.go
- K8s collector delete bugfix
- Modify agent install parameter validation check
- Change helmchart image tag information
=> Collector delete bugfix

file/templates/default.tick, pkg/api/core/alert/task/task.go, pkg/api/core/alert/types/types.go, pkg/storage/metricstore/influxdb/v1/influxdb.go
1. Add Kapacitor http-post alert
2. Metric look-up bugfix
=> Add Kapacitor http-post alert & Metric look-up bugfix

helm/cb-dragonfly/templates/_helpers.tpl, helm/cb-dragonfly/templates/serviceaccount.yaml, helm/cb-dragonfly/values.yaml
Make sure that deployment named 'collector' have the right to deploy & modify & delete k8s resources.
=> [Update helm] Add Cluster-role & Role-Binding

pkg/api/core/agent/common/common.go, pkg/api/core/agent/mcis/configure.go
=> [Cortado] MCIS DEBIAN OS 지원

pkg/api/apiserver.go, pkg/api/rest/metric/mcis/metric.go, pkg/storage/metricstore/influxdb/metric/metric.go, pkg/storage/metricstore/influxdb/v1/query.go
* vm 모니터링 필요한 파라미터를 넣어주기 위해 api 변경
* Disk 메트릭 항목 업데이트 안되서 발생한 버그 해결
* 메모리, 네트워크 메트릭 조회 이슈 해결
=> bugfix get vm monitoring info

build-image.sh, helm/cb-dragonfly/Chart.yaml
=> helm version update

pkg/api/core/agent/mcis/configure.go, pkg/modules/monitoring/push/mcis/collector_scheduler.go
- Kafka  연결 에러 처리 개선
- Pulbic IP 확인 기능 포함 에이전트 패키지 업데이트
=> [Hotfix] Scheduler, Agent Package(update)
